<?php
// Plugin definition
$plugin = array(
  'title' => t('Türen'),
  'icon' => 'tueren.png',
  'category' => t('Responsive'),
  'theme' => 'tueren',
  'css' => 'tueren.css',
  'regions' => array(
    'header' => t('Header'),
    'sidebar' => t('Sidebar'),
    'contentheader' => t('Content Header'),
    'contentcolumn1' => t('Content Column 1'),
    'contentcolumn2' => t('Content Column 2'),
    'contentfooter' => t('Content Footer'),
  ),
);
